version: '3'

services:

   node-server:
        build: .
        restart: unless-stopped
        env_file:
            - example.env
        volumes:
            - .:/app
        command: /bin/sh -c "yarn start"